#spring.application.name=hospitalsystem
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/HospitalSystem
    username: root
    password: admin123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
    format-sql: true
  mvc:
    servlet:
      path: /api/v1
  mail:
    host: smtp.gmail.com
    port: 587
    username: "trikhaikhmt@gmail.com"
    password: "zqzz icyx nyme kkbh"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  secret: "jBpoQbllxjqpDuO/9T4qTWkiMnGWhtazhidIaHx0DNA="
  expiration: 2592000000 # 30 ngày = 2_592_000_000 ms
fileUpload:
  rootPath: uploads
  patient:
    rootPath: uploads/patient
  doctor:
    rootPath: uploads/doctor
  drug:
    rootPath: uploads/drug